### ISSUE TITLE
solve this error regarding boolean.

### ISSUE THREAD

**Issue by 23BCA284** [vtcbca/oop-programming-assignment-1-23BCA284#1]
![oopbooleanerror](https://github.com/user-attachments/assets/97dfe2ac-371d-4c90-96e6-c0e1563eb199)
please help me to solve this error.

**Comment by 23bca286** [comment]
please replace bool variable "Found" as integer.

like below:

int found=0 

inside for loop replace found="True" with found=1.

outside for loop in if write as : if(found==0)

please try and check..its solve.

**Comment by 23BCA284** [comment]
Great...Thank you so much....Error solve and i got appropriate output.
